apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-job
spec:
  template:
    spec:
      containers:
      - name: fetch
        image: alpine
        command: ['/bin/sh', '-c', 'wget http://blue-green.com'] 
      restartPolicy: Never